config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :doses, only: [:delete, :new, :create] do
  root to: 'cocktails#index'
  resources :cocktails, only: [:show, :new, :create] do
    resources :doses, only: [:destroy, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, :cocktail, :ingredient, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :cocktails_count
  private

  def cocktails_count
    @cocktail_length = Cocktail.all.size
  end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: "Cocktail was succesfully created."
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredients = Ingredient.all
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@dose.cocktail), notice: "Dose was succesfully created."
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail), notice: "Dose was succesfully deleted."
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

# < simple_form_for [@coctails, @dose]

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="box" id="title">
  <h1>I feel bad for people who don’t drink. When they wake up in the morning, that’s as good as they’re going to feel all day.
<br>~ Frank Sinatra</h1>
</div>

<div class="box container-lazy-scrolling">


<!--   <h1>All the cocktails</h1> -->


  <ul id="cards-list">
    <% @cocktails.each do |cocktail| %>
    <!-- <div class="col-12 col-md-6 col-lg-4"> -->
      <li class="list-item">

        <%= link_to cocktail_path(cocktail) do %>
       <!--  <div class="cocktail-image"> -->

          <% if cocktail.photo.attached? %>

            <%= cl_image_tag cocktail.photo.key, loading: "lazy", width: 394, height: 494, crop: :fill, class: 'cocktail-image' %>
          <% else %>
          <!-- <div class="card-pic" style="background-image: url('https://res.cloudinary.com/dfphdhnpb/image/upload/v1605272798/m3x6otcommpqtg9d1dsi.jpg', <%#= loading: 'lazy' %>)"></div> -->
            <%#= image_tag "https://res.cloudinary.com/dfphdhnpb/image/upload/v1605297646/m3x6otcommpqtg9d1dsi.jpg", alt: "alttext",  loading: "lazy", class: "card-pic" %>
            <%= cl_image_tag("wtmebrgogthuicufdkgl", width: 394, height: 494, crop: :fill, loading: "lazy", class: 'cocktail-image') %>
          <% end %>
       <!--  </div> -->
          <p class='cocktail-image'><%= cocktail.name %></p>
        <% end %>
      </li>
<!--     </div> -->
    <% end %>

  </ul>
</div>

app/views/cocktails/new.html.erb
<div class="box">
  <h3>“Sometimes a work of art comes in a glass.”
~ Anthony T Hincks</h3>
  <%= simple_form_for(@cocktail) do |f| %>
    <%= f.input :name, placeholder: "Name", label: false %>
    <div class="photo-input">
      <%= f.input :photo, as: :file %>
    </div>

    <div class="submit-button">
      <%= f.button :submit, "+ Create new cocktail" %>
    </div>

  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="box">
<div>
  <div class="image-of-the-cocktail">
    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key, height: 484, width: 797, crop: :fill %>
    <% else %>
      <%= cl_image_tag("wtmebrgogthuicufdkgl", alt: "alttext", height: 484, width: 797, crop: :fill ) %>
    <% end %>
    <h2><%= @cocktail.name %></h2>
  </div>
  <div class="cocktail-doses">
    <% @cocktail.doses.each do |dose| %>
      <h4><%= dose.ingredient.name %><span><%= link_to '   -', cocktail_dose_path(@cocktail, dose.id), method: :delete, data: { confirm: 'Are you sure?' } %></span></h4>
      <p><%= dose.description %></p>

    <% end %>
    <%= link_to "+ Add a new dose", new_cocktail_dose_path(@cocktail) %>
  </div>
</div>





</div>

app/views/doses/index.html.erb
<h1>Hello</h1>

app/views/doses/new.html.erb
<div class="box">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>

  <%= f.button :submit, "+ Create new dose" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="cursor"></div>
    <%= render "shared/navbar" %>

    <div class="wrapper">
      <%= yield %>
    </div>


    <%= render "shared/footer" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.1.2/lazysizes.min.js" async></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.0.0/TweenMax.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/animation.gsap.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js"></script>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer" id="footer">
  <div class="footer-links">
    <a href="#">facebook</a>
    <a href="#">vimeo</a>
    <a href="#">instagram</a>
    <a href="#">twitter</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to root_path, class: "header-logo" do %>
    <%= image_tag asset_path('cock.jpeg'), alt: "Logo", class: "avatar avatar-bordered" %>
    <p>COCKTAIL&GARNISH</p>
  <% end %>
  </a>
  <div class="header-links">
   <%= link_to root_path do %>
     <span>cocktails</span>
     <sup><%= @cocktail_length %></sup>
   <% end %>
   <%= link_to "create", new_cocktail_path, class: "margin-left" %>
   <%= link_to "contact", root_path(anchor: 'footer'), class: "margin-left" %>
  </div>
</div>